version: '3.6'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  receiver:
    image: 04110000/mqservice-receiver:latest
    environment:
      - spring.rabbitmq.host=rabbitmq
    links:
      - rabbitmq



